Repository ArkEcosystem/go-crypto, pull requests merged in 2020-02, with the labels that each got.

#64 Update HTLC claim to support secret of 32 bytes
  crypto/builder_test.go
  crypto/deserializer.go
  crypto/fixtures/transactions/htlc_claim/passphrase-no-vendor-field.json
  crypto/serializer.go
Labels: Complexity: Low

#67 release: 1.0.0
  CHANGELOG.md
Labels: Complexity: Low, Type: Release

#68 chore: fix wrong release year
  CHANGELOG.md
Labels: Complexity: Low, Type: Task
